name: Purge Cache
on:
  page_build
jobs:
  purge_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Run purge cache script
        env:
          SECRET_PAGE_PURGE_CACHE_SCRIPT: ${{ secrets.SECRET_PAGE_PURGE_CACHE_SCRIPT }}
        run: eval "$SECRET_PAGE_PURGE_CACHE_SCRIPT" > /dev/null
